AUTH_PROVIDERS = [{"type": "local"}]
SERVER_NAME = "localhost:8000"
SECRET_KEY = "your_secret_key_here"
SQLALCHEMY_DATABASE_URI = "postgresql://kadi:your_secret_key_here@postgres/kadi"
STORAGE_PATH = "/opt/kadi/storage"
MISC_UPLOADS_PATH = "/opt/kadi/uploads"
SMTP_HOST = "localhost"
SMTP_PORT = 25
SMTP_USERNAME = ""
SMTP_PASSWORD = ""
MAIL_NO_REPLY = "no-reply@kadi4mat.example.com"